CREATE DATABASE my_karaoke IDENTIFIED BY 1234;

CREATE TABLE PERSON IF NOT EXISTS(
	id number primary key,
	name varchar2(10),
	gender varchar2(10),
	room varchar2(4)
);

CREATE SEQUENCE IF NOT EXISTS person_id_seq;

INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"KIM_1","FEMALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"KIM_2","MALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"KIM_3","FEMALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"LEE_1","MALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"LEE_2","MALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"LEE_3","FEMALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"LEE_4","MALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"LEE_5","FEMALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"PARK_1","MALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"PARK_2","MALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"PARK_3","FEMALE","B");
INSERT INTO PERSON VALUES (person_id_seq.NEXTVAL,"PARK_4","MALE","B");
